config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :users, only: [:show, :update, :destroy] do
    resources :task_lists, controller: 'users/task_lists' do
      member do
        patch 'toggle_bookmark'
      end
      resources :tasks, controller: 'users/task_lists/tasks', only: [:index, :update, :create, :destroy]
    end
  end

  #public task lists
  resources :public_task_lists, only: [:index, :show] do
    member do
      patch 'toggle_bookmark'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite_task_list.rb
class FavoriteTaskList < ActiveRecord::Base
  belongs_to :user
  belongs_to :task_list
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :description, presence: true

  belongs_to :task_list

  scope :from_task_list, lambda { |task_list_id| where(task_list_id: task_list_id) }
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  
  validates :name, presence: true

  belongs_to :user
  has_many :tasks

  has_many :favorite_task_lists
  has_many :users_who_favored, through: :favorite_task_lists, source: :user


  scope :from_user, lambda { |user_id| where(user_id: user_id) }
  scope :publics, lambda { where(public: true)}

  def toggle_bookmark_for(user_id)
    if is_bookmarked_by?(user_id)
      unbookmark(user_id)
    else
      bookmark(user_id)      
    end      
  end

  def bookmark(user_id)
    FavoriteTaskList.where(user_id: user_id, task_list_id: self.id).first_or_create
  end

  def unbookmark(user_id)
    FavoriteTaskList.where(user_id: user_id, task_list_id: self.id).destroy_all
  end

  def is_bookmarked_by?(user_id)
    FavoriteTaskList.where(user_id: user_id, task_list_id: self.id).present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, :name, :password, presence: true

  has_many :task_lists

  has_many :favorite_task_lists
  has_many :favorited_task_lists, through: :favorite_task_lists, source: :task_list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      'devise'
    else
      'application'
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    if resource.is_a?(User) && user_signed_in?
      user_task_lists_path(resource)
    else
      super
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/public_task_lists_controller.rb
class PublicTaskListsController < ApplicationController
  before_action :authenticate_user!
  def index
    @task_lists = TaskList.publics
  end

  def show
    @task_list = TaskList.find(params[:id])
  end

  def toggle_bookmark
    task_list = TaskList.find(params[:id])
    task_list.toggle_bookmark_for(current_user.id)
    redirect_to public_task_lists_path
  end
end

app/controllers/users/task_lists/tasks_controller.rb
class Users::TaskLists::TasksController < ApplicationController
  before_action :authenticate_user!
  def index
    @task_list = TaskList.find(params[:task_list_id])
    @tasks = @task_list.tasks.sort
    @task = Task.new
  end

  def create
    @task = Task.create(params[:task].permit!)
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes!(params[:task].permit!)
    render json: @task
  end

  def destroy
    @id = params[:id]
    Task.find(@id).destroy
  end
end

app/controllers/users/task_lists_controller.rb
class Users::TaskListsController < ApplicationController
  
  before_action :authenticate_user!

  def index
    @task_lists = TaskList.from_user(params[:user_id])
  end

  def create
    TaskList.create(params[:task_list].permit!)
    redirect_to user_task_lists_path(params[:user_id])
  end

  def update
    task_list = TaskList.find(params[:id])
    task_list.update_attributes(params[:task_list].permit!)
    redirect_to user_task_lists_path(params[:user_id])
  end

  def new
    @task_list = TaskList.new
  end

  def edit; end

  def destroy
    @id = params[:id]
    TaskList.destroy(@id)
  end

  def toggle_bookmark
    task_list = TaskList.find(params[:id])
    task_list.toggle_bookmark_for(params[:user_id])
    redirect_to user_task_lists_path(params[:user_id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_class_for_attr_public(task_list)
    if task_list.public?
      'fa fa-check-square-o fa-2x'
    else
      'fa fa-square-o fa-2x'
    end
  end

  def set_class_for_attr_completed(task)
    if task.completed?
      'line-through'
    else
      ''
    end
  end

  def set_class_for_attr_bookmarked(task_list)
    if task_list.is_bookmarked_by?(current_user)
      'fa fa-star fa-2x'
    else
      'fa fa-star-o fa-2x'
    end
  end

end

app/views/home/index.html.erb
<main class="app-logo">
	<h1>Acme</h1>
  <h2>TO-DO lists</h2>
  <div class="anvil">
  </div>
</main>
<section class="about">
	<article>
		<h3>Need to catch a Roadrunner?</h3>
		<div>
			<%= image_tag "roadrunner.png"%>
			<p>
				Our brand new todo list app will keep you organized and will increase your chances,
				dont lose your time and <%= link_to "Sign Up", new_user_session_path  %> in our app.
			</p>
		</div>
	</article>
	<hr>
</section>

app/views/layouts/_user_nav.html.erb
<header>
  <nav>
    <ul>
      <li>
        <%= link_to "My lists", user_task_lists_path(current_user), class: 'not-change-color'%>
      </li>
      <li>
        <%= link_to "Browse public lists", public_task_lists_path, class: 'not-change-color'%>
      </li>
      <li class="u-pull-right">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'not-change-color'%>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/_visitant_nav.html.erb
<header>
  <nav>
    <ul>
      <li>
        <%= link_to "Sign In", new_user_session_path, class: 'not-change-color'%>
      </li>
      <li>
        <%= link_to "Sign Up", new_user_registration_path, class: 'not-change-color'%>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= render partial: 'layouts/user_nav' %>
    <% else %>
      <%= render partial: 'layouts/visitant_nav' %>
    <% end %>
    <% if flash.present?%>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>

    <!-- <footer>
        &reg; Acme Anvil Corp. All rights... and lefts too reserved!
    </footer> -->

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% if flash.present?%>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
  </body>
</html>

app/views/public_task_lists/index.html.erb
<main class="container">
    <div class="app-logo">
      <h1><%=link_to "Acme", root_path, class: 'not-change-color' %></h1>
    </div>
  <div class="row">
    <div class="twelve columns">
      <div class="user-lists">
        <% if !@task_lists.present? %>
          <h2 class="nothing-here">
            There's no public task lists in the system =(
          </h2>
        <% else %>
          <h2>
            Public TO-DO lists
          </h2>
          <table class="u-full-width">
            <thead>
              <tr>
                <th>Name</th>
                <th>Favorite</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @task_lists.each do |task_list| %>
                <tr data-id="<%= task_list.id %>" data-user-id="<%= task_list.user_id %>" data-public="<%= task_list.public %>">
                  <td><%= task_list.name %></td>
                  <td>
                    <%= button_tag class: "icon pub-fav" do %>
                      <i class="<%= set_class_for_attr_bookmarked(task_list) %>" aria-hidden="true"></i>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to(public_task_list_path(task_list.id), class: 'button') do %>
                      <span>tasks</span>
                      <i class="fa fa-arrow-right fa-2x" aria-hidden="true"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
         
            <p>You can click in the star icon to favorite/unfavorite the task lists</p>
            <p>Click in the button tasks to see the tasks of a task list</p>
          
        <% end %> 
      </div>
    </div>
  </div>
</main>

app/views/public_task_lists/show.html.erb
<main class="container">
  <div class="app-logo">
    <h1><%=link_to "Acme", root_path, class: 'not-change-color' %></h1>
  </div>
  <div class="row">
    <div class="twelve columns">
      <div class="list-tasks">
          <%= link_to 'Back', public_task_lists_path, class: 'back-icon u-pull-right' %>
          <h2>
            <%= @task_list.name %>
          </h2>
          <% @task_list.tasks.each do |task| %>
            <div class="row">
              <div class="form-inputs task-form">
                <div class="twelve columns">
                  <%= text_field_tag 'task[description]', task.description, class: set_class_for_attr_completed(task), disabled: true %></p>
                </div>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/task_lists/destroy.js.erb
$("#user-lists tr[data-id=<%= @id %>]").fadeOut( "slow" );

app/views/users/task_lists/index.html.erb
<main class="container">
  <div class="app-logo">
    <h1><%=link_to "Acme", root_path, class: 'not-change-color' %></h1>
  </div>
  <div class="row">
    <div class="twelve columns">
      <div class="user-lists">
        <% if !@task_lists.present? %>
          <h2 class="nothing-here">
            It seems that there is no list here!
          </h2>
          <%= link_to "Create One!", new_user_task_list_path, class: "button" %>
        <% else %>
          <%= link_to new_user_task_list_path(current_user), class: 'button u-pull-right', id: 'new-task' do %>
            <span>New</span>
            <i class="fa fa-plus fa-2x" aria-hidden="true"></i>
          <% end %>
          <h2>
            TO-DO lists
          </h2>
          <table class="u-full-width">
            <thead>
              <tr>
                <th>Name</th>
                <th>Public</th>
                <th>Favorite</th>
                <th span="2"></th>
              </tr>
            </thead>
            <tbody>
              <% @task_lists.each do |task_list| %>
                <tr data-id="<%= task_list.id %>" data-user-id="<%= task_list.user_id %>" data-public="<%= task_list.public %>">
                  <td><%= task_list.name %></td>
                  <td>
                    <%= button_tag class: 'icon update-public' do %>
                      <i class="<%= set_class_for_attr_public(task_list) %>" aria-hidden="true"></i>
                    <% end %>
                  </td>
                  <td>
                    <%= button_tag class: "icon fav" do %>
                      <i class="<%= set_class_for_attr_bookmarked(task_list) %>" aria-hidden="true"></i>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to(user_task_list_path(id: task_list.id), class: 'button', remote: true, method: :delete) do %>
                      <span>delete</span>
                      <i class="fa fa-trash-o fa-2x" aria-hidden="true"></i>
                    <% end %>
                     <%= link_to(user_task_list_tasks_path(current_user.id, task_list.id), class: 'button') do %>
                      <span>tasks</span>
                      <i class="fa fa-arrow-right fa-2x" aria-hidden="true"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
            <p>You can click in the star icon to favorite/unfavorite the task list</p>
            <p>You can click in the check box to make a task list public or private</p>
            <p>Click in the button tasks to see the tasks of a task list</p>
        <% end %> 
      </div>
    </div>
  </div>
</main>

app/views/users/task_lists/new.html.erb
<main class="container">
  <div class="app-logo">
    <h1><%=link_to "Acme", root_path, class: 'not-change-color' %></h1>
  </div>
  <div class="row">
    <div class="twelve columns">
      <div class="user-lists">
          <h2>TO-DO Lists</h2>
        <div class="form">
          <%= simple_form_for([:user, @task_list], remote: true) do |f| %>
            <div class="form-inputs">
              <%= f.input :name, required: true, autofocus: true, as: :string %>
              <%= f.input :public, required: true %>
              <%= f.input :user_id, as: :hidden, input_html: { value: params[:user_id] } %>
            </div>

            <div class="form-actions">
              <%= f.button :submit, "Create" %>
            </div>
          <% end %>

          <%= link_to 'Back', user_task_lists_path(current_user.id), class: 'back-icon u-pull-left' %>
        </div> 
      </div>
    </div>
  </div>
</main>

app/views/users/task_lists/tasks/_task.html.erb
<div class="row">
  <div class="form-inputs task-form" data-completed="<%= task.completed %>" data-task-list-id="<%= task.task_list_id %>" data-user-id="<%= current_user.id %>" data-id="<%= task.id %>">
    <div class="eleven columns task-desc">
      <%= text_field_tag 'task[description]', task.description, class: set_class_for_attr_completed(task) %></p>
    </div>
    <div class="one column">
      <%= link_to(user_task_list_task_path(current_user.id, task.task_list.id, task.id), class: 'icon trash', remote: true, method: :delete) do %>
        <i class="fa fa-trash-o fa-2x" aria-hidden="true"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/users/task_lists/tasks/create.js.erb
$(':input','#new_task')
 .not(':button, :submit, :reset, :hidden')
 .val('');

$('.list-tasks').append(
  "<%= j render partial: 'task', locals: {task: @task } %>"
);

$('#new_task').find('input[type=text]').focus();

app/views/users/task_lists/tasks/destroy.js.erb
debugger;

$(".task-form[data-id=<%= @id %>]").closest('.row').fadeOut( "slow" );

app/views/users/task_lists/tasks/index.html.erb
<main class="container">
  <div class="app-logo">
    <h1><%=link_to "Acme", root_path, class: 'not-change-color' %></h1>
  </div>
  <div class="row">
    <div class="twelve columns">
      <div class="list-tasks">
          <%= link_to 'Back', user_task_lists_path(current_user.id), class: 'back-icon u-pull-right' %>
          <h2>
            <%= @task_list.name %>
          </h2>
          <%= simple_form_for(@task, url: user_task_list_tasks_path(current_user, @task_list), remote: true) do |f| %> 
            <%= f.error_notification %>
            <div class="row">
              <div class="form-inputs task-form">
                <div class="twelve columns">
                  <%= f.input :description, required: false, as: :string, label: false, placeholder: 'Enter your task here and press enter when finished' %>
                  <%= f.input :task_list_id, as: :hidden, input_html: { value: @task_list.id } %>
                </div>
              </div>
            </div>

          <% end %>
          <% @tasks.each do |task| %>
            <%= render partial: 'task', locals: { task: task } %>
          <% end %>
            <p>You can edit a existent task by clicking in the text editing it and then press enter to save</p>
            <p>double click in the task to mark it as completed</p>
      </div>
    </div>
  </div>
</main>